import {
  bucketOf,
  bucketPath,
  KANJI_JLPT_PATH,
  type DictBucket,
  type DictEntry,
  type DictManifest,
  type KanjiJlptIndex,
} from './types';

/**
 * Read access to the dictionary that ships inside the app (`public/dict/jmdict/`, generated by
 * `npm run build:dict` — CI does this for every APK).
 *
 * The dictionary is sharded by a hash of each headword ({@link bucketOf}), so a lookup only reads
 * the one or two small files its candidate forms hash into. Everything is local, so lookups work
 * offline from the first launch with nothing to download.
 */

/** Where the bundled dictionary lives. Overridable for development against a separately hosted copy. */
const BASE = (import.meta.env.VITE_DICT_BASE as string | undefined) ?? '/dict/jmdict';

/** Parsed buckets held for the session; they are small and re-parsing on every lookup is waste. */
const memory = new Map<number, DictBucket>();
/** In-flight reads, so N candidate forms in one bucket cause one read, not N. */
const inFlight = new Map<number, Promise<DictBucket>>();

/**
 * Fetch a `.json.gz` file and parse it. Some servers (Vite's dev server among them) label `.gz`
 * files `Content-Encoding: gzip`, so the browser has already inflated the body — check the gzip
 * magic bytes rather than trusting either behaviour.
 */
async function fetchGzipJson<T>(path: string, what: string): Promise<T> {
  let res: Response;
  try {
    res = await fetch(`${BASE}/${path}`);
  } catch {
    throw new Error(`Couldn’t read ${what}.`);
  }
  if (res.status === 404) throw new Error('The dictionary isn’t included in this build.');
  if (!res.ok) throw new Error(`Couldn’t read ${what} (${res.status}).`);
  const bytes = new Uint8Array(await res.arrayBuffer());
  const gzipped = bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b;
  const text = gzipped
    ? await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text()
    : new TextDecoder().decode(bytes);
  return JSON.parse(text) as T;
}

// ---- Manifest ---------------------------------------------------------------

let manifestPromise: Promise<DictManifest> | null = null;

export function getManifest(): Promise<DictManifest> {
  manifestPromise ??= (async () => {
    const res = await fetch(`${BASE}/manifest.json`).catch(() => null);
    if (!res || !res.ok) throw new Error('The dictionary isn’t included in this build.');
    const manifest = (await res.json()) as DictManifest;
    if (manifest.format !== 'buckets-1') throw new Error(`Unsupported dictionary format "${manifest.format}".`);
    return manifest;
  })();
  manifestPromise.catch(() => {
    manifestPromise = null;
  });
  return manifestPromise;
}

// ---- Buckets ----------------------------------------------------------------

function getBucket(bucket: number): Promise<DictBucket> {
  const held = memory.get(bucket);
  if (held) return Promise.resolve(held);
  const pending = inFlight.get(bucket);
  if (pending) return pending;
  const p = fetchGzipJson<DictBucket>(bucketPath(bucket), 'the dictionary')
    .then((data) => {
      memory.set(bucket, data);
      return data;
    })
    .finally(() => inFlight.delete(bucket));
  inFlight.set(bucket, p);
  return p;
}

/** Every entry filed under any of `forms`, de-duplicated by id. */
export async function entriesForForms(forms: string[]): Promise<DictEntry[]> {
  const wanted = [...new Set(forms.filter(Boolean))];
  if (wanted.length === 0) return [];
  const manifest = await getManifest();

  const byBucket = new Map<number, string[]>();
  for (const form of wanted) {
    const b = bucketOf(form, manifest.bucketCount);
    const list = byBucket.get(b);
    if (list) list.push(form);
    else byBucket.set(b, [form]);
  }

  const out: DictEntry[] = [];
  const seen = new Set<string>();
  const loaded = await Promise.all([...byBucket].map(async ([bucket, bucketForms]) => [await getBucket(bucket), bucketForms] as const));
  for (const [data, bucketForms] of loaded) {
    for (const form of bucketForms) {
      for (const entry of data[form] ?? []) {
        if (seen.has(entry.id)) continue;
        seen.add(entry.id);
        out.push(entry);
      }
    }
  }
  return out;
}

// ---- Kanji JLPT index -------------------------------------------------------

let kanjiJlptPromise: Promise<KanjiJlptIndex> | null = null;

/** `literal → old-JLPT level` for every kanji in KANJIDIC (drives the reader's "N3+" furigana). */
export function getKanjiJlpt(): Promise<KanjiJlptIndex> {
  kanjiJlptPromise ??= fetchGzipJson<KanjiJlptIndex>(KANJI_JLPT_PATH, 'the kanji index');
  kanjiJlptPromise.catch(() => {
    kanjiJlptPromise = null;
  });
  return kanjiJlptPromise;
}
