import {
  bucketOf,
  bucketPath,
  KANJI_JLPT_PATH,
  type DictBucket,
  type DictEntry,
  type DictManifest,
  type KanjiJlptIndex,
} from './types';
import { BundledAssetMissing, fetchBundledGzip } from './bundledAsset';

/**
 * Read access to the dictionary that ships inside the app (`public/dict/jmdict/`, generated by
 * `npm run build:dict` — CI does this for every APK).
 *
 * The dictionary is sharded by a hash of each headword ({@link bucketOf}), so a lookup only reads
 * the one or two small files its candidate forms hash into. Everything is local, so lookups work
 * offline from the first launch with nothing to download.
 */

/** Where the bundled dictionary lives. Overridable for development against a separately hosted copy. */
const BASE = (import.meta.env.VITE_DICT_BASE as string | undefined) ?? '/dict/jmdict';

/** Parsed buckets held for the session; they are small and re-parsing on every lookup is waste. */
const memory = new Map<number, DictBucket>();
/** In-flight reads, so N candidate forms in one bucket cause one read, not N. */
const inFlight = new Map<number, Promise<DictBucket>>();

/** Fetch a bundled `.json.gz` file ({@link fetchBundledGzip} handles every way it can arrive) and parse it. */
async function fetchGzipJson<T>(path: string, what: string): Promise<T> {
  let bytes: Uint8Array;
  try {
    bytes = await fetchBundledGzip(`${BASE}/${path}`);
  } catch (e) {
    if (e instanceof BundledAssetMissing) throw new Error('The dictionary isn’t included in this build.');
    throw new Error(`Couldn’t read ${what}. ${e instanceof Error ? e.message : String(e)}`);
  }
  return JSON.parse(new TextDecoder().decode(bytes)) as T;
}

// ---- Manifest ---------------------------------------------------------------

let manifestPromise: Promise<DictManifest> | null = null;

export function getManifest(): Promise<DictManifest> {
  manifestPromise ??= (async () => {
    const res = await fetch(`${BASE}/manifest.json`).catch(() => null);
    if (!res || !res.ok) throw new Error('The dictionary isn’t included in this build.');
    const manifest = (await res.json()) as DictManifest;
    if (manifest.format !== 'buckets-1') throw new Error(`Unsupported dictionary format "${manifest.format}".`);
    return manifest;
  })();
  manifestPromise.catch(() => {
    manifestPromise = null;
  });
  return manifestPromise;
}

// ---- Buckets ----------------------------------------------------------------

function getBucket(bucket: number): Promise<DictBucket> {
  const held = memory.get(bucket);
  if (held) return Promise.resolve(held);
  const pending = inFlight.get(bucket);
  if (pending) return pending;
  const p = fetchGzipJson<DictBucket>(bucketPath(bucket), 'the dictionary')
    .then((data) => {
      memory.set(bucket, data);
      return data;
    })
    .finally(() => inFlight.delete(bucket));
  inFlight.set(bucket, p);
  return p;
}

/** Every entry filed under any of `forms`, de-duplicated by id. */
export async function entriesForForms(forms: string[]): Promise<DictEntry[]> {
  const wanted = [...new Set(forms.filter(Boolean))];
  if (wanted.length === 0) return [];
  const manifest = await getManifest();

  const byBucket = new Map<number, string[]>();
  for (const form of wanted) {
    const b = bucketOf(form, manifest.bucketCount);
    const list = byBucket.get(b);
    if (list) list.push(form);
    else byBucket.set(b, [form]);
  }

  const out: DictEntry[] = [];
  const seen = new Set<string>();
  const loaded = await Promise.all([...byBucket].map(async ([bucket, bucketForms]) => [await getBucket(bucket), bucketForms] as const));
  for (const [data, bucketForms] of loaded) {
    for (const form of bucketForms) {
      for (const entry of data[form] ?? []) {
        if (seen.has(entry.id)) continue;
        seen.add(entry.id);
        out.push(entry);
      }
    }
  }
  return out;
}

// ---- Kanji JLPT index -------------------------------------------------------

let kanjiJlptPromise: Promise<KanjiJlptIndex> | null = null;

/** `literal → old-JLPT level` for every kanji in KANJIDIC (drives the reader's "N3+" furigana). */
export function getKanjiJlpt(): Promise<KanjiJlptIndex> {
  kanjiJlptPromise ??= fetchGzipJson<KanjiJlptIndex>(KANJI_JLPT_PATH, 'the kanji index');
  kanjiJlptPromise.catch(() => {
    kanjiJlptPromise = null;
  });
  return kanjiJlptPromise;
}
